spring:
    h2:
        console:
            enabled: true
            path: /h2-console

    data:
        web:
            pageable:
                one-indexed-parameters: true
                default-page-size: 5

    datasource:
        url: jdbc:h2:mem:fixadate
        username: sa
        password:
        driver-class-name: org.h2.Driver

    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                #        show_sql: true
                format_sql: true

logging:
    level:
        org.hibernate.SQL: debug
        org.hibernate.type: trace


server:
    error:
        include-exception: true
        include-message: always

google:
    client:
        id: 120890874732-gbu01labf2gh9id7hkauropgeuubjpun.apps.googleusercontent.com
        pw: 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